# generated by datamodel-codegen:
#   filename:  implementation_plan.json
#   timestamp: 2026-06-07T03:05:32+00:00

from __future__ import annotations
from typing import Literal, Any, Annotated
from pydantic import BaseModel, ConfigDict, Field


ImplementationPlanTitle = Annotated[
    str,
    Field(pattern=r"^Implementation \d+ Plan$")
]


class Metadata(BaseModel):
  model_config = ConfigDict(extra="forbid")

  document_id: Annotated[str, Field(pattern=r"^implementation_plan_\d+\.json$")]
  title: ImplementationPlanTitle
  purpose: Literal["This file outlines an implementation plan."]
  source_format: Literal["json"]
  document_authority: Literal["operational_state"]


class ImplementationPlan(BaseModel):
  model_config = ConfigDict(extra="forbid")

  metadata: Metadata
  implementation_intent: list[Any]
  project_manager_report: str
  planned_work: list[Any]
  non_goals: list[Any]
  acceptance_criteria: list[Any]
  current_repo_runtime_state: list[Any]
  assumptions_and_unknowns: list[Any]
  affected_surfaces: list[Any]
  non_affected_surfaces: list[Any]
  completion_rules: list[Any]
  approval_gates: list[Any]
  closeout_notes: list[Any]
