# generated by datamodel-codegen:
#   filename:  implementation_plan.json
#   timestamp: 2026-06-07T03:05:32+00:00

from __future__ import annotations
from typing import Literal, Annotated
from pydantic import BaseModel, ConfigDict, Field


ImplementationPlanTitle = Annotated[
  str,
  Field(pattern=r"^Implementation \d+ Plan$")
]


class Metadata(BaseModel):
  model_config = ConfigDict(extra="forbid")

  document_id: Annotated[str, Field(pattern=r"^implementation_plan_\d+\.json$")]
  title: ImplementationPlanTitle
  purpose: Literal["This file outlines an implementation plan."]
  source_format: Literal["json"]
  document_authority: Literal["operational_state"]


class ImplementationIntent(BaseModel):
  model_config = ConfigDict(extra="forbid")

  id: str
  summary: str
  why_it_matters: str


class Seam(BaseModel):
  model_config = ConfigDict(extra="forbid")

  id: str
  title: str
  description: str
  status: Literal[
    "active",
    "proposed",
    "complete", 
    "blocked"
  ] = "proposed"
  evidence_target: list[str]


class AcceptanceCriterion(BaseModel):
  model_config = ConfigDict(extra="forbid")

  id: str
  criterion: str
  required_evidence: list[str]


class CurrentRepoState(BaseModel):
  model_config = ConfigDict(extra="forbid")

  surface: str
  state: str
  notes: str


class AssumptionOrUnknown(BaseModel):
  model_config = ConfigDict(extra="forbid")

  id: str
  type: str
  statement: str
  risk_if_wrong: str


class ApprovalGate(BaseModel):
  model_config = ConfigDict(extra="forbid")

  id: str
  boundary: str
  requires: str


class ImplementationPlan(BaseModel):
  model_config = ConfigDict(extra="forbid")

  metadata: Metadata
  implementation_intent: list[ImplementationIntent]
  project_manager_report: str
  seams: list[Seam]
  non_goals: list[str]
  acceptance_criteria: list[AcceptanceCriterion]
  current_repo_runtime_state: list[CurrentRepoState]
  assumptions_and_unknowns: list[AssumptionOrUnknown]
  affected_surfaces: list[str]
  non_affected_surfaces: list[str]
  completion_rules: list[str]
  approval_gates: list[ApprovalGate]
  closeout_notes: list[str]
