# generated by datamodel-codegen:
#   filename:  governance_primitives.json
#   timestamp: 2026-06-06T18:41:54+00:00

from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field


class Metadata(BaseModel):
    model_config = ConfigDict(extra="forbid")

    document_id: Literal["governance_primitives.json"]
    title: Literal["Governance Primitives"]
    context: Literal["Governance for ./project_spec.json defining project-local authority semantics, approval boundaries, admissible transformations, and review scaffolding."]
    purpose: str
    source_format: Literal["json"]
    document_authority: Literal["invariant_authority_object"]


class ObservabilityScaffolding(BaseModel):
    artifact_paths: list[str]
    runtime_identity: list[str]
    runtime_results: list[str]
    authority_manifests: list[str]
    repo_state: list[str]
    status_values: list[str]


class GovernancePosture(BaseModel):
    invariant_constraints: list[str]
    observability_scaffolding: ObservabilityScaffolding
    explicit_distinctions: list[str]


class ExplicitApprovalRequiredToModify(BaseModel):
    governance_project_spec: list[str]
    schema_: list[str] = Field(..., alias='schema')
    agent_contract: list[str]
    api_and_model_behavior: list[str]
    auth: list[str]
    storage: list[str]
    deployment: list[str]
    destructive_operation: list[str]
    broad_architecture: list[str]
    compatibility_and_fallback_commitment: list[str]
    project_intent_dependent_behavior: list[str]


class ApprovalBoundaries(BaseModel):
    explicit_approval_required_to_modify: ExplicitApprovalRequiredToModify


class OrderItem(BaseModel):
    rank: int
    id: str
    description: str


class TaskAuthority(BaseModel):
    order: list[OrderItem]
    description: str
    conflict_handling: str
    task_authorization: str
    agent_authority_boundary: list[str]


class Sources(BaseModel):
    authoritative_artifacts: list[str]
    derived_artifacts: list[str]
    operational_artifacts: list[str]
    presentation_artifacts: list[str]
    order: str


class VerificationDuties(BaseModel):
    must_not_skip: list[str]


class AmbiguityUncertainty(BaseModel):
    preserve_visibility: list[str]


class NamedAdmissibilityInputs(BaseModel):
    invariant_constraints: list[str]
    task_constraints: str
    constraint_conflicts: list[str]
    admissibility_checks: str
    stop_conditions: list[str]


class InvariantsAndIntegrityConstraints(BaseModel):
    task_authority: TaskAuthority
    sources: Sources
    fixtures_samples_test_roles: list[str]
    compatibility_commitments: list[str]
    verification_duties: VerificationDuties
    ambiguity_uncertainty: AmbiguityUncertainty
    named_admissibility_inputs: NamedAdmissibilityInputs


class AdmissibleTransformations(BaseModel):
    preserve_project_spec: list[str]
    require_open_decision: list[str]
    amend_project_spec_or_governance: list[str]
    preserve_provenance_or_inspectability: list[str]
    forbidden_shortcuts: list[str]
    evidence_minimum: list[str]


class VisibleBeforeTrusting(BaseModel):
    source_authority: list[str]
    derived_or_operational_artifacts: list[str]
    synthesis_automation_ux: list[str]


class ReviewCheckpoints(BaseModel):
    visible_before_trusting: VisibleBeforeTrusting
    visible_before_closing_work: list[str]


class RuntimePathRequired(BaseModel):
    command: str
    args: list[str]


class SavedArtifact(BaseModel):
    id: str
    path_pattern: str
    required: bool


class EvidenceRequired(BaseModel):
    saved_artifacts: list[SavedArtifact]


class AcceptanceProbe(BaseModel):
    id: str
    question: str
    runtime_path_required: RuntimePathRequired
    evidence_required: EvidenceRequired


class GovernancePrimitives(BaseModel):
    field_schema: str = Field(..., alias='$schema')
    metadata: Metadata
    governance_posture: GovernancePosture
    approval_boundaries: ApprovalBoundaries
    invariants_and_integrity_constraints: InvariantsAndIntegrityConstraints
    admissible_transformations: AdmissibleTransformations
    review_checkpoints: ReviewCheckpoints
    acceptance_probes: list[AcceptanceProbe]
    not_proof: list[str]
