# generated by datamodel-codegen:
#   filename:  known_failures.json
#   timestamp: 2026-06-06T19:23:06+00:00

from __future__ import annotations
from typing import Literal, Any
from pydantic import BaseModel, ConfigDict, Field


class Metadata(BaseModel):
  model_config = ConfigDict(extra="forbid")

  document_id: Literal["known_failures.json"]
  title: Literal["Known Failures"]
  source_format: Literal["json"]
  document_authority: Literal["invariant_authority_object"]

class Entry(BaseModel):
  model_config = ConfigDict(extra="forbid")

  id: str
  pattern: str
  trigger: str
  symptom: str
  likely_cause: str
  prevention_rule: str
  easiest_check: str
  last_seen: str
  status: str


class KnownFailures(BaseModel):
  model_config = ConfigDict(extra="forbid")

  field_schema: str = Field(..., alias='$schema')
  metadata: Metadata
  purpose: str
  usage_rules: list[str]
  entries_schema_ref: Literal["./KnownFailureEntry.schema.json"]
  entries: list[Entry]
