# generated by datamodel-codegen:
#   filename:  open_decisions.json
#   timestamp: 2026-06-06T19:37:04+00:00

from __future__ import annotations
from typing import Literal, Any
from pydantic import BaseModel, ConfigDict, Field


class Metadata(BaseModel):
  model_config = ConfigDict(extra="forbid")

  document_id: Literal["open_decisions.json"]
  title: Literal["Open Decisions"]
  source_format: Literal["json"]
  document_authority: Literal["operational_state"]


class OpenDecisions(BaseModel):
  model_config = ConfigDict(extra="forbid")

  field_schema: str = Field(..., alias='$schema')
  metadata: Metadata
  purpose: str
  usage_rules: list[str]
  current_decisions: list[Any]
  pending_decisions: list[Any]
  notes: list[Any]
