# generated by datamodel-codegen:
#   filename:  project_spec.json
#   timestamp: 2026-06-06T02:20:17+00:00

from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field


class Metadata(BaseModel):
  model_config = ConfigDict(extra="forbid")

  document_id: Literal["project_spec.json"]
  title: Literal["Project Spec"]
  purpose: str
  source_format: Literal["json"]
  document_authority: Literal["harness_target"]


class ProjectIsNot(BaseModel):
  model_config = ConfigDict(extra="forbid")

  excluded_product_forms: list[str]
  excluded_agent_patterns: list[str]
  design_guardrail: list[str]


class ProjectExistsTo(BaseModel):
  model_config = ConfigDict(extra="forbid")

  delineate_boundaries: list[str]
  instantiate_governance: list[str]


class HighestValueWorkflow(BaseModel):
  model_config = ConfigDict(extra="forbid")

  command: str
  args: list[str]
  expectations: list[str]
  stop_condition: str


class ProjectThesis(BaseModel):
  model_config = ConfigDict(extra="forbid")

  project_is: list[str]
  project_is_not: ProjectIsNot
  project_exists_to: ProjectExistsTo
  core_runtime_shape: list[str]
  primary_operator: str
  highest_value_workflow: HighestValueWorkflow


class NonGoals(BaseModel):
  model_config = ConfigDict(extra="forbid")

  do_not_build: list[str]
  do_not_fake: list[str]
  do_not_smooth_over: list[str]
  do_not_preserve_without_approval: list[str]


class RequiredInspectableSurfaces(BaseModel):
  model_config = ConfigDict(extra="forbid")

  default_location: str
  min_required_artifacts: list[str]
  optional_debug_artifacts: list[str]
  authoritative_context_artifact: str
  authoritative_pm_runtime_output_artifacts: str


class Dependencies(BaseModel):
  model_config = ConfigDict(extra="forbid")

  required: list[str]
  excluded: list[str]


class ArchitecturalShape(BaseModel):
  model_config = ConfigDict(extra="forbid")

  required_runtime_surfaces: list[str]
  required_evidence_boundaries: list[str]
  required_inspectable_surfaces: RequiredInspectableSurfaces
  dependencies: Dependencies
  runtime_constraints: list[str]
  governance_primitives_constraints: list[str]
  forbidden_surfaces: list[str]
  deferred_surfaces: list[str]


class AuthoritativeBoundaries(BaseModel):
  model_config = ConfigDict(extra="forbid")

  authoritative_sources: list[str]
  authoritative_memory: list[str]
  agents_must_respect: list[str]


class RuntimeDiscipline(BaseModel):
  model_config = ConfigDict(extra="forbid")

  must_exist: list[str]
  meaningful_progress_metrics: list[str]
  authoritative_boundaries: AuthoritativeBoundaries


class ProjectQualityBar(BaseModel):
  model_config = ConfigDict(extra="forbid")

  ux_properties: list[str]
  evidence_expectations: list[str]
  runtime_expectations: list[str]
  non_trivial_quality_markers: list[str]
  operator_expectations: list[str]
  inspectability_properties: list[str]


class RuntimePathRequired(BaseModel):
  model_config = ConfigDict(extra="forbid")

  command: str
  args: list[str]


class SavedArtifact(BaseModel):
  model_config = ConfigDict(extra="forbid")

  id: str
  path_pattern: str
  required: bool


class EvidenceRequired(BaseModel):
  model_config = ConfigDict(extra="forbid")

  saved_artifacts: list[SavedArtifact]


class AcceptanceProbe(BaseModel):
  model_config = ConfigDict(extra="forbid")

  id: str
  question: str
  runtime_path_required: RuntimePathRequired
  evidence_required: EvidenceRequired
  not_proof: list[str]


class ClarifyingQuestions(BaseModel):
  model_config = ConfigDict(extra="forbid")

  material_decisions: list[str]
  probe_sources: str
  external_call_privacy_constraints: list[str]
  acceptable_deferrals: list[str]


class ProjectSpec(BaseModel):
  model_config = ConfigDict(extra="forbid")

  schema_ref: str = Field(..., alias='$schema')
  metadata: Metadata
  project_thesis: ProjectThesis
  non_goals: NonGoals
  architectural_shape: ArchitecturalShape
  runtime_discipline: RuntimeDiscipline
  project_quality_bar: ProjectQualityBar
  acceptance_probes: list[AcceptanceProbe]
  clarifying_questions: ClarifyingQuestions
