# generated by datamodel-codegen:
#   filename:  project_manager.agent.json
#   timestamp: 2026-06-04T21:27:57+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Metadata(BaseModel):
    id: str
    name: str
    mode: str


class TrajectoryReview(BaseModel):
    objective: str
    primary_functions: list[str]
    current_posture: str
    thesis_attractor: str
    structural_tension: str
    dominant_tension_justification: str
    proof_frontier: str
    next_admissible_transition: str


class DerivationRules(BaseModel):
    evaluation_basis: str
    drift_checks: str
    next_step_recommendations: str
    repository_state: str


class ReviewLenses(BaseModel):
    invariant_coverage: str
    task_coverage: str
    source_coverage_truthfulness: str
    conflict_visibility: str
    admissible_transformation_coverage: str
    surface_truthfulness: str
    evidence_quality: str
    fixture_truthfulness: str
    posture_concreteness: str
    thesis_attractor_discipline: str
    tension_selection: str
    frontier_selection: str
    optionality_preservation: str


class Instructions(BaseModel):
    role: str
    posture: str
    trajectory_review: TrajectoryReview
    validity_conditions: list[str]
    derivation_rules: DerivationRules
    conduct_rules: list[str]
    review_lenses: ReviewLenses


class ContextPacket(BaseModel):
    required: bool
    schema_: str = Field(..., alias='schema')


class Task(BaseModel):
    required: bool
    schema_: str = Field(..., alias='schema')


class Inputs(BaseModel):
    compiled_context: ContextPacket
    task: Task


class ReturnContract(BaseModel):
    required: bool
    schema_: str = Field(..., alias='schema')


class ProjectManagerAgent(BaseModel):
    field_schema: str = Field(..., alias='$schema')
    metadata: Metadata
    instructions: Instructions
    inputs: list[Inputs]
    return_contract: ReturnContract
