# generated by datamodel-codegen:
#   filename:  project_manager.agent.json
#   timestamp: 2026-06-05T12:49:34+00:00

from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field


class Metadata(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str
    name: str
    mode: str


class TrajectoryReview(BaseModel):
    model_config = ConfigDict(extra="forbid")

    objective: str
    primary_functions: list[str]
    current_posture: str
    thesis_attractor: str
    structural_tension: str
    dominant_tension_justification: str
    proof_frontier: str
    next_admissible_transition: str


class DerivationRules(BaseModel):
    model_config = ConfigDict(extra="forbid")

    evaluation_basis: str
    drift_checks: str
    next_step_recommendations: str
    repository_state: str


class ReviewLenses(BaseModel):
    model_config = ConfigDict(extra="forbid")

    invariant_coverage: str
    task_coverage: str
    source_coverage_truthfulness: str
    conflict_visibility: str
    admissible_transformation_coverage: str
    surface_truthfulness: str
    evidence_quality: str
    fixture_truthfulness: str
    posture_concreteness: str
    thesis_attractor_discipline: str
    tension_selection: str
    frontier_selection: str
    optionality_preservation: str


class Instructions(BaseModel):
    model_config = ConfigDict(extra="forbid")

    role: str
    posture: str
    trajectory_review: TrajectoryReview
    validity_conditions: list[str]
    derivation_rules: DerivationRules
    conduct_rules: list[str]
    review_lenses: ReviewLenses


class ProjectContextPacket(BaseModel):
    model_config = ConfigDict(extra="forbid")

    required: bool
    authoritative: bool
    document: str
    schema_: str = Field(..., alias='schema')


class Task(BaseModel):
    model_config = ConfigDict(extra="forbid")

    required: bool
    authoritative: bool
    document: str
    schema_: str = Field(..., alias='schema')


class Input(BaseModel):
    model_config = ConfigDict(extra="forbid")

    project_context_packet: ProjectContextPacket
    task: Task


class ReturnContract(BaseModel):
    model_config = ConfigDict(extra="forbid")

    required: bool
    schema_: str = Field(..., alias='schema')


class Output(BaseModel):
    model_config = ConfigDict(extra="forbid")

    return_contract: ReturnContract


class ProjectManagerAgent(BaseModel):
    model_config = ConfigDict(extra="forbid")

    field_schema: str = Field(..., alias='$schema')
    metadata: Metadata
    instructions: Instructions
    input: list[Input]
    output: list[Output]
