# generated by datamodel-codegen:
#   filename:  project_manager.agent.json
#   timestamp: 2026-06-08T20:26:58+00:00

from __future__ import annotations
from typing import Literal, Any
from pydantic import BaseModel, ConfigDict, Field


class Metadata(BaseModel):
  model_config = ConfigDict(extra="forbid")

  id: str
  agent_name: str


class StatusSemantics(BaseModel):
  model_config = ConfigDict(extra="forbid")

  admissible: Literal["The task can proceed under current project and task authority."]
  admissibility_blocked: Literal["The PM cannot judge or proceed because required basis, context, or authority is missing."]
  rejected: Literal["The task conflicts with invariant project or harness authority."]
  needs_clarification: Literal["The task is ambiguous enough that user clarification is required, but no invariant conflict is established."]


class ProjectManagerReportDerivationRules(BaseModel):
  model_config = ConfigDict(extra="forbid")

  evaluation_basis: str
  drift_checks: str
  next_step_recommendations: str
  repository_state: str
  status_semantics: StatusSemantics


class ReviewLenses(BaseModel):
  model_config = ConfigDict(extra="forbid")

  invariant_coverage: str
  task_coverage: str
  source_coverage_truthfulness: str
  conflict_visibility: str
  admissible_transformation_coverage: str
  surface_truthfulness: str
  evidence_quality: str
  fixture_truthfulness: str
  posture_concreteness: str
  thesis_attractor_discipline: str
  tension_selection: str
  frontier_selection: str
  optionality_preservation: str


class InstructionContract(BaseModel):
  model_config = ConfigDict(extra="forbid")

  role: str
  posture: str
  objective: str
  validity_conditions: list[str]
  project_manager_report_derivation_rules: ProjectManagerReportDerivationRules
  conduct_rules: list[str]
  review_lenses: ReviewLenses


class ProjectContextPacket(BaseModel):
  model_config = ConfigDict(extra="forbid")

  required: bool
  schema_ref: Literal["../project_spec/ProjectContextPacket.schema.json"]


class Task(BaseModel):
  model_config = ConfigDict(extra="forbid")

  required: bool
  schema_ref: Literal["../runtime/Task.schema.json"]


class RuntimeInputs(BaseModel):
  model_config = ConfigDict(extra="forbid")

  project_context_packet: ProjectContextPacket
  task: Task


class ProjectManagerReport(BaseModel):
  model_config = ConfigDict(extra="forbid")

  required: bool
  schema_ref: Literal["../contracts/ProjectManagerReport.schema.json"]


class RuntimeOutputs(BaseModel):
  model_config = ConfigDict(extra="forbid")

  project_manager_report: ProjectManagerReport


class ProjectManagerAgent(BaseModel):
  model_config = ConfigDict(extra="forbid")

  schema_ref: str = Field(..., alias='$schema')
  metadata: Metadata
  model: str
  instruction_contract: InstructionContract
  runtime_inputs: RuntimeInputs
  runtime_outputs: RuntimeOutputs
  tool_permissions: list[Any]
