# generated by datamodel-codegen:
#   filename:  project_manager_report.json
#   timestamp: 2026-06-08T15:20:58+00:00

from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field


class Metadata(BaseModel):
  model_config = ConfigDict(extra="forbid")

  document_id: Literal["project_manager_report.json"]
  title: Literal["Project Manager Report"]
  source_format: Literal["json"]
  document_authority: Literal["generated_artifact"]


class ReportSourceCoverageEntry(BaseModel):
  model_config = ConfigDict(extra="forbid")

  consumed: bool
  basis: list[str]

class ReportSourceCoverage(BaseModel):
  model_config = ConfigDict(extra="forbid")

  project_context_packet: ReportSourceCoverageEntry
  task: ReportSourceCoverageEntry


class DriftDetection(BaseModel):
  model_config = ConfigDict(extra="forbid")

  drift_detected: bool
  description: str | None = None


class TrajectoryReview(BaseModel):
  model_config = ConfigDict(extra="forbid")

  current_posture: str
  thesis_attractor: str
  drift_detection: DriftDetection
  invariant_constraints: list[str]
  task_constraints: list[str]
  structural_tension: str


class ProofFrontier(BaseModel):
  model_config = ConfigDict(extra="forbid")

  constraint_conflicts: list[str]
  dominant_tension_justification: str
  blocked: bool
  blocking_reason: str | None = None
  next_admissible_transformation: str | None = None
  affected_surfaces: list[str]
  non_affected_surfaces: list[str]
  stop_conditions: list[str]


class ProjectManagerReport(BaseModel):
  model_config = ConfigDict(extra="forbid")

  metadata: Metadata
  report_status: Literal[
    "admissible",
    "admissibility_blocked",
    "rejected",
    "needs_clarification",
  ]
  report_summary: str
  report_source_coverage: ReportSourceCoverage
  trajectory_review: TrajectoryReview
  proof_frontier: ProofFrontier
