# generated by datamodel-codegen:
#   filename:  project_manager_report.schema.json
#   timestamp: 2026-06-04T14:16:18+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class Evidence(BaseModel):
    description: str
    title: str
    type: str


class AnyOfItem(BaseModel):
    type: str


class MissingBasis(BaseModel):
    anyOf: list[AnyOfItem]
    default: None
    description: str
    title: str


class Name(BaseModel):
    description: str
    title: str
    type: str


class Status(BaseModel):
    description: str
    enum: list[str]
    title: str
    type: str


class Properties(BaseModel):
    evidence: Evidence
    missing_basis: MissingBasis
    name: Name
    status: Status


class AdmissibilityCheck(BaseModel):
    additionalProperties: bool
    properties: Properties
    required: list[str]
    title: str
    type: str


class Items(BaseModel):
    type: str


class Findings(BaseModel):
    description: str
    items: Items
    minItems: int
    title: str
    type: str


class MissingBasis1(BaseModel):
    description: str
    items: Items
    title: str
    type: str


class Properties1(BaseModel):
    findings: Findings
    missing_basis: MissingBasis1
    status: Status


class ReportSection(BaseModel):
    additionalProperties: bool
    properties: Properties1
    required: list[str]
    title: str
    type: str


class ClaimsSupported(BaseModel):
    description: str
    items: Items
    title: str
    type: str


class Reason(BaseModel):
    anyOf: list[AnyOfItem]
    default: None
    description: str
    title: str


class SourceId(BaseModel):
    description: str
    title: str
    type: str


class Used(BaseModel):
    description: str
    title: str
    type: str


class Properties2(BaseModel):
    claims_supported: ClaimsSupported
    reason: Reason
    source_id: SourceId
    used: Used


class SourceCoverage(BaseModel):
    additionalProperties: bool
    properties: Properties2
    required: list[str]
    title: str
    type: str


class FieldDefs(BaseModel):
    AdmissibilityCheck_1: AdmissibilityCheck = Field(..., alias='AdmissibilityCheck')
    ReportSection_1: ReportSection = Field(..., alias='ReportSection')
    SourceCoverage_1: SourceCoverage = Field(..., alias='SourceCoverage')


class Items3(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class AdmissibilityChecks(BaseModel):
    items: Items3
    minItems: int
    title: str
    type: str


class AffectedSurfaces(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class AllowedTransformationTypes(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class ConstraintConflicts(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class CurrentPosture(BaseModel):
    description: str
    title: str
    type: str


class DominantTensionJustification(BaseModel):
    description: str
    title: str
    type: str


class InvariantConstraints(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class NextAdmissibleTransition(BaseModel):
    description: str
    title: str
    type: str


class NonAffectedSurfaces(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class ProofFrontier(BaseModel):
    description: str
    title: str
    type: str


class SourceCoverage1(BaseModel):
    items: Items3
    minItems: int
    title: str
    type: str


class StopConditions(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class StructuralTension(BaseModel):
    description: str
    title: str
    type: str


class Summary(BaseModel):
    description: str
    title: str
    type: str


class TaskConstraints(BaseModel):
    field_ref: str = Field(..., alias='$ref')


class ThesisAttractor(BaseModel):
    description: str
    title: str
    type: str


class Properties3(BaseModel):
    admissibility_checks: AdmissibilityChecks
    affected_surfaces: AffectedSurfaces
    allowed_transformation_types: AllowedTransformationTypes
    constraint_conflicts: ConstraintConflicts
    current_posture: CurrentPosture
    dominant_tension_justification: DominantTensionJustification
    invariant_constraints: InvariantConstraints
    next_admissible_transition: NextAdmissibleTransition
    non_affected_surfaces: NonAffectedSurfaces
    proof_frontier: ProofFrontier
    source_coverage: SourceCoverage1
    status: Status
    stop_conditions: StopConditions
    structural_tension: StructuralTension
    summary: Summary
    task_constraints: TaskConstraints
    thesis_attractor: ThesisAttractor


class Model(BaseModel):
    field_defs: FieldDefs = Field(..., alias='$defs')
    additionalProperties: bool
    properties: Properties3
    required: list[str]
    title: str
    type: str
