# generated by datamodel-codegen:
#   filename:  project_manager_report.json
#   timestamp: 2026-06-08T15:20:58+00:00

from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field,  model_validator


class Metadata(BaseModel):
  model_config = ConfigDict(extra="forbid")

  document_id: Literal["project_manager_report.json"]
  title: Literal["Project Manager Report"]
  source_format: Literal["json"]
  document_authority: Literal["generated_artifact"]


class ReportSourceCoverageEntry(BaseModel):
  model_config = ConfigDict(extra="forbid")

  consumed: bool
  basis: list[str]

class ReportSourceCoverage(BaseModel):
  model_config = ConfigDict(extra="forbid")

  project_context_packet: ReportSourceCoverageEntry
  task: ReportSourceCoverageEntry


class DriftDetection(BaseModel):
  model_config = ConfigDict(extra="forbid")

  drift_detected: bool
  description: str | None


class TrajectoryReview(BaseModel):
  model_config = ConfigDict(extra="forbid")

  current_posture: str
  thesis_attractor: str
  drift_detection: DriftDetection
  invariant_constraints: list[str]
  task_constraints: list[str]
  structural_tension: str


class ProofFrontier(BaseModel):
  model_config = ConfigDict(extra="forbid")

  constraint_conflicts: list[str]
  dominant_tension_justification: str | None

  blocked: bool
  blocking_reason: str | None
  missing_basis: list[str]

  next_admissible_transformation: str | None
  affected_surfaces: list[str] | None
  non_affected_surfaces: list[str] | None
  stop_conditions: list[str] | None

  @model_validator(mode="after")
  def enforce_blocking_reason_when_blocked(self):
    if self.blocked and not self.blocking_reason:
      raise ValueError(
        "blocking_reason is required when proof_frontier.blocked is true."
      )

    if not self.blocked and self.blocking_reason is not None:
      raise ValueError(
        "blocking_reason must be null when proof_frontier.blocked is false."
      )

    return self


class ProjectManagerReport(BaseModel):
  model_config = ConfigDict(extra="forbid")

  metadata: Metadata
  report_status: Literal[
    "admissible",
    "admissibility_blocked",
    "rejected",
    "needs_clarification",
  ]
  report_summary: str
  report_source_coverage: ReportSourceCoverage
  trajectory_review: TrajectoryReview
  proof_frontier: ProofFrontier

  @model_validator(mode="after")
  def enforce_status_matches_blocked_state(self):
    if self.report_status == "admissible" and self.proof_frontier.blocked:
      raise ValueError(
        "report_status cannot be 'admissible' when proof_frontier.blocked is true."
      )

    if self.report_status == "admissibility_blocked" and not self.proof_frontier.blocked:
      raise ValueError(
        "report_status cannot be 'admissibility_blocked' when proof_frontier.blocked is false."
      )

    return self

  @model_validator(mode="after")
  def enforce_status_and_blocked_coherence(self):
    if self.report_status == "admissible" and self.proof_frontier.blocked:
      raise ValueError(
          "Invalid PM report: report_status is 'admissible' but proof_frontier.blocked is true."
      )

    if self.report_status == "admissibility_blocked" and not self.proof_frontier.blocked:
      raise ValueError(
          "Invalid PM report: report_status is 'admissibility_blocked' but proof_frontier.blocked is false."
      )

    return self