# generated by datamodel-codegen:
#   filename:  project_manager_report.json
#   timestamp: 2026-06-08T15:20:58+00:00

from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field


class Metadata(BaseModel):
  model_config = ConfigDict(extra="forbid")

  document_id: Literal["project_manager_report.json"]
  title: Literal["Project Manager Report"]
  source_format: Literal["json"]
  document_authority: Literal["generated_artifact"]


class ReportSourceCoverageItem(BaseModel):
  model_config = ConfigDict(extra="forbid")

  runtime_inputs_name: str
  consumed: bool
  basis: list[str]


class DriftDetection(BaseModel):
  model_config = ConfigDict(extra="forbid")

  drift_detected: bool
  description_if_present: str


class TrajectoryReview(BaseModel):
  model_config = ConfigDict(extra="forbid")

  current_posture: str
  thesis_attractor: str
  drift_detection: DriftDetection
  invariant_constraints: list[str]
  task_constraints: list[str]
  structural_tension: str


class ProofFrontier(BaseModel):
  model_config = ConfigDict(extra="forbid")

  constraint_conflicts: list[str]
  dominant_tension_justification: str
  next_admissible_transformation: str
  affected_surfaces: list[str]
  non_affected_surfaces: list[str]
  stop_conditions: list[str]


class ProjectManagerReport(BaseModel):
  model_config = ConfigDict(extra="forbid")

  metadata: Metadata
  report_status: Literal[
      "admissible", 
      "admissibility_blocked", 
      "rejected", 
      "needs_clarification"
      ]
  report_summary: str
  report_source_coverage: list[ReportSourceCoverageItem] = Field(min_length=1)
  trajectory_review: TrajectoryReview
  proof_frontier: ProofFrontier
