# generated by datamodel-codegen:
#   filename:  implementation_tracker.json
#   timestamp: 2026-06-07T03:21:51+00:00

from __future__ import annotations
from typing import Literal, Any
from pydantic import BaseModel, ConfigDict, Field


class Metadata(BaseModel):
  model_config = ConfigDict(extra="forbid")

  document_id: Literal["implementation_tracker.json"]
  title: Literal["Implementation <#> Tracker"]
  purpose: Literal["This file tracks an implementation plan."]
  source_format: Literal["json"]
  document_authority: Literal["generated_artifact"]


class TrackerItem(BaseModel):
  model_config = ConfigDict(extra="forbid")

  date: str
  seam: str
  agent: str
  change: str
  evidence: str
  status: Literal[
      "proposed",
      "active",
      "blocked",
      "reviewing",
      "archived"
  ]


class Blocker(BaseModel):
  model_config = ConfigDict(extra="forbid")

  blocker: str
  boundary: str
  owner_agent: str
  resolution: str


class ImplementationTracker(BaseModel):
  model_config = ConfigDict(extra="forbid")

  field_schema: str = Field(..., alias='$schema')
  metadata: Metadata
  status: str
  state: Literal[
      "proposed",
      "active",
      "blocked",
      "reviewing",
      "archived"
  ]
  tracker: list[TrackerItem]
  blockers: list[Blocker]
  closeout_notes: list[str]
