# generated by datamodel-codegen:
#   filename:  governance_primitives.json
#   timestamp: 2026-06-09T21:07:19+00:00

from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field

BindingAuthority = Literal[
    "global_harness",
    "harness_target",
    "runtime_policy",
    "operational_state",
]

DerivedRuntimeArtifact = Literal[
    "compiled_runtime_artifact",
    "output_policy_artifact",
    "raw_provider_artifact",
]

AgentContracts = Literal[
  "project_manager",
  "planning_manager",
  "review_manager",
  "red_team_manager",
  "implementation_manager",
  "archive_manager",
  "worker_adapter"
  ]

ApprovalSensitiveSurfaces = Literal[
  "global_harness",
  "agent_contracts",
  "output_policies",
  "runtime_orchestration",
  "tool_and_worker_surface",
  "provider_or_api_behavior",
  "compatibility_commitments"
  ]

class Metadata(BaseModel):
  model_config = ConfigDict(extra="forbid")

  document_id: Literal["governance_primitives.json"]
  title: Literal["Governance Primitives"]
  context: Literal["Global governance for the CLI harness. These primitives govern agent operation, execution boundaries, runtime artifact semantics, and authority separation in every target repository the harness is placed inside and invoked against."]
  purpose: Literal["Define and delineate global harness-level invariants from harness target repository boundaries that every project workflow must respect."]
  source_format: Literal["json"]
  document_authority: Literal["global_harness"]


class DocumentAuthorityClasses(BaseModel):
  model_config = ConfigDict(extra="forbid")

  binding_authority: list[BindingAuthority]
  derived_runtime_artifacts: list[DerivedRuntimeArtifact]


class GovernancePrimitives(BaseModel):
  model_config = ConfigDict(extra="forbid")

  schema_ref: str = Field(..., alias='$schema')
  metadata: Metadata
  document_authority_classes: DocumentAuthorityClasses
  agent_contracts: list[AgentContracts]
  approval_sensitive_surfaces: list[ApprovalSensitiveSurfaces] = []
