# generated by datamodel-codegen:
#   filename:  runtime_budget.policy.json
#   timestamp: 2026-06-04T01:59:58+00:00

from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field


class RuntimeBudgetDefaults(BaseModel):
  model_config = ConfigDict(extra="forbid")

  max_input_tokens: int = Field(gt=0)
  reserved_output_tokens: int = Field(gt=0)
  oversize_strategy: Literal ["fail_or_batch"]
  truncation: Literal ["disabled"]


class RuntimeBudgetPolicy(BaseModel):
  model_config = ConfigDict(extra="forbid")
  
  schema_ref: str | None = Field(default=None, alias="$schema")
  default: RuntimeBudgetDefaults
