# generated by datamodel-codegen:
#   filename:  task.json
#   timestamp: 2026-06-06T20:09:25+00:00

from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field


class Metadata(BaseModel):
  model_config = ConfigDict(extra="forbid")

  document_id: Literal["task.json"]
  title: Literal["Task"]
  purpose: Literal["This file assigns the task to the agent."]
  source_format: Literal["json"]
  document_authority: Literal["task_authority"]


class TaskItem(BaseModel):
  model_config = ConfigDict(extra="forbid")

  task_text: str
  created_at: str
  requested_agent: str
  run_id: str


class Task(BaseModel):
  model_config = ConfigDict(extra="forbid")

  field_schema: str = Field(..., alias='$schema')
  metadata: Metadata
  task: list[TaskItem]
