# generated by datamodel-codegen:
#   filename:  project_context_packet.json
#   timestamp: 2026-06-05T12:29:08+00:00

from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field


class Metadata(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str
    name: str


class ProjectSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")
    
    required: bool
    authoritative: bool
    document: Literal["./project_spec.json"]
    schema_ref: Literal["./ProjectSpec.schema.json"]


class GovernancePrimitives(BaseModel):
    model_config = ConfigDict(extra="forbid")

    required: bool
    authoritative: bool
    document: Literal["./governance_primitives.json"]
    schema_ref: Literal["./GovernancePrimitives.schema.json"]


class KnownFailures(BaseModel):
    model_config = ConfigDict(extra="forbid")

    required: bool
    authoritative: bool
    document: Literal["./known_failures.json"]
    schema_ref: Literal["./KnownFailures.schema.json"]


class OpenDecisions(BaseModel):
    model_config = ConfigDict(extra="forbid")

    required: bool
    authoritative: bool
    document: Literal["./open_decisions.json"]
    schema_ref: Literal["./OpenDecisions.schema.json"]


class ProjectContextPacket(BaseModel):
    model_config = ConfigDict(extra="forbid")

    schema_ref: str | None = Field(default=None, alias="$schema")
    metadata: Metadata
    project_spec: ProjectSpec
    governance_primitives: GovernancePrimitives
    known_failures: KnownFailures
    open_decisions: OpenDecisions
