# generated by datamodel-codegen:
#   filename:  project_context_packet.json
#   timestamp: 2026-06-05T12:29:08+00:00

from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field


class Metadata(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str
    name: str


class ProjectSpec(BaseModel):
    model_config = ConfigDict(extra="forbid")
    
    required: bool
    authoritative: bool
    document: str
    schema_: str = Field(..., alias='schema')


class GovernancePrimitives(BaseModel):
    model_config = ConfigDict(extra="forbid")

    required: bool
    authoritative: bool
    document: str
    schema_: str = Field(..., alias='schema')


class KnownFailures(BaseModel):
    model_config = ConfigDict(extra="forbid")

    required: bool
    authoritative: bool
    document: str
    schema_: str = Field(..., alias='schema')


class OpenDecisions(BaseModel):
    model_config = ConfigDict(extra="forbid")

    required: bool
    authoritative: bool
    document: str
    schema_: str = Field(..., alias='schema')


class ProjectContextPacket(BaseModel):
    model_config = ConfigDict(extra="forbid")

    schema_ref: str | None = Field(default=None, alias="$schema")
    metadata: Metadata
    project_spec: ProjectSpec
    governance_primitives: GovernancePrimitives
    known_failures: KnownFailures
    open_decisions: OpenDecisions
